-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."user"
(
    email character varying NOT NULL,
    password character varying NOT NULL,
    PRIMARY KEY (email)
);

COMMENT ON TABLE public."user"
    IS 'This is a database user';

CREATE TABLE IF NOT EXISTS public.task
(
    title character varying NOT NULL,
    description character varying NOT NULL,
    code integer NOT NULL GENERATED ALWAYS AS IDENTITY,
    subtask integer,
    "user" character varying,
    PRIMARY KEY (code)
);

COMMENT ON TABLE public.task
    IS 'This is a task created by a user';

ALTER TABLE IF EXISTS public.task
    ADD CONSTRAINT subtask_fk FOREIGN KEY (subtask)
    REFERENCES public.task (code) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.task
    ADD CONSTRAINT user_fk FOREIGN KEY ("user")
    REFERENCES public."user" (email) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;